# Generated by Django 5.0.14 on 2026-06-22 02:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auditorias', '0001_initial'),
        ('empresas', '0001_initial'),
        ('pesv', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoSoporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='documentos_soporte/%Y/')),
                ('descripcion', models.CharField(blank=True, max_length=255)),
                ('fecha_documento', models.DateField(blank=True, null=True, verbose_name='Fecha del documento')),
                ('fecha_vigencia_hasta', models.DateField(blank=True, null=True, verbose_name='Vigente hasta')),
                ('version', models.PositiveIntegerField(default=1)),
                ('vigente', models.BooleanField(default=True, help_text='Desmarcar cuando este documento sea reemplazado por una versión más reciente.')),
                ('fecha_carga', models.DateTimeField(auto_now_add=True)),
                ('cargado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('componente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documentos_soporte', to='pesv.componente')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos_soporte', to='empresas.empresa')),
            ],
            options={
                'verbose_name': 'Documento soporte',
                'verbose_name_plural': 'Documentos soporte',
                'ordering': ['-fecha_carga'],
            },
        ),
        migrations.CreateModel(
            name='EvidenciaEjecucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_archivo', models.CharField(choices=[('DOCUMENTO', 'Documento'), ('FOTO', 'Fotografía')], default='DOCUMENTO', max_length=10)),
                ('archivo', models.FileField(upload_to='evidencias_ejecucion/%Y/')),
                ('descripcion', models.CharField(blank=True, max_length=255)),
                ('fecha_evidencia', models.DateField(blank=True, null=True, verbose_name='Fecha de la evidencia')),
                ('fecha_carga', models.DateTimeField(auto_now_add=True)),
                ('auditoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evidencias', to='auditorias.auditoria')),
                ('cargado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('componente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evidencias_ejecucion', to='pesv.componente')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidencias_ejecucion', to='empresas.empresa')),
            ],
            options={
                'verbose_name': 'Evidencia de ejecución',
                'verbose_name_plural': 'Evidencias de ejecución',
                'ordering': ['-fecha_carga'],
            },
        ),
    ]
