# Generated by Django 5.0.14 on 2026-06-22 02:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0001_initial'),
        ('pesv', '0001_initial'),
        ('programa', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Auditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('hora_inicio', models.TimeField(blank=True, null=True)),
                ('hora_fin', models.TimeField(blank=True, null=True)),
                ('lugar', models.CharField(blank=True, max_length=255)),
                ('estado', models.CharField(choices=[('EN_PROCESO', 'En proceso'), ('FINALIZADA', 'Finalizada (pendiente de cierre)'), ('CERRADA', 'Cerrada / informe emitido')], default='EN_PROCESO', max_length=12)),
                ('resumen_ejecutivo', models.TextField(blank=True)),
                ('fecha_elaboracion_informe', models.DateField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('componentes_auditados', models.ManyToManyField(blank=True, related_name='auditorias', to='pesv.componente')),
                ('elaborado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='informes_elaborados', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auditorias', to='empresas.empresa')),
                ('equipo_auditor', models.ManyToManyField(blank=True, related_name='auditorias_realizadas', to=settings.AUTH_USER_MODEL)),
                ('pasos_auditados', models.ManyToManyField(blank=True, related_name='auditorias', to='pesv.pasopesv')),
                ('visita', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auditorias', to='programa.visitaprogramada')),
            ],
            options={
                'verbose_name': 'Auditoría',
                'verbose_name_plural': 'Auditorías',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Hallazgo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('CONFORMIDAD', 'Conformidad'), ('NO_CONFORMIDAD', 'No conformidad'), ('OBSERVACION', 'Observación'), ('RECOMENDACION', 'Recomendación')], max_length=15)),
                ('descripcion', models.TextField()),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('auditoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hallazgos', to='auditorias.auditoria')),
                ('componente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hallazgos', to='pesv.componente')),
            ],
            options={
                'verbose_name': 'Hallazgo',
                'verbose_name_plural': 'Hallazgos',
                'ordering': ['tipo', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AccionMejora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.TextField(verbose_name='Acción de mejora')),
                ('responsable', models.CharField(blank=True, max_length=200)),
                ('fecha_compromiso', models.DateField(verbose_name='Fecha de cumplimiento comprometida')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_PROCESO', 'En proceso'), ('CUMPLIDA', 'Cumplida'), ('VENCIDA', 'Vencida')], default='PENDIENTE', max_length=12)),
                ('fecha_cierre', models.DateField(blank=True, null=True)),
                ('evidencia_cierre', models.FileField(blank=True, null=True, upload_to='planes_mejora/evidencias_cierre/')),
                ('observaciones_seguimiento', models.TextField(blank=True)),
                ('hallazgo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acciones_mejora', to='auditorias.hallazgo')),
            ],
            options={
                'verbose_name': 'Acción del plan de mejoramiento',
                'verbose_name_plural': 'Plan de mejoramiento',
                'ordering': ['fecha_compromiso'],
            },
        ),
        migrations.CreateModel(
            name='ItemEvaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calificacion', models.CharField(choices=[('CUMPLE', 'Cumple'), ('CUMPLE_PARCIAL', 'Cumple parcialmente'), ('NO_CUMPLE', 'No cumple'), ('NO_APLICA', 'No aplica'), ('SIN_EVALUAR', 'Sin evaluar')], default='SIN_EVALUAR', max_length=15)),
                ('observaciones', models.TextField(blank=True)),
                ('auditoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items_evaluados', to='auditorias.auditoria')),
                ('componente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items_evaluados', to='pesv.componente')),
            ],
            options={
                'verbose_name': 'Item evaluado',
                'verbose_name_plural': 'Items evaluados',
                'ordering': ['componente__orden'],
                'unique_together': {('auditoria', 'componente')},
            },
        ),
    ]
