# Generated by Django 5.0.14 on 2026-06-22 02:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InstrumentoInspeccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('LISTA_CHEQUEO', 'Lista de chequeo'), ('ENTREVISTA', 'Formato de entrevista'), ('INSPECCION_FISICA', 'Formato de inspección física'), ('ENCUESTA', 'Encuesta / cuestionario'), ('OTRO', 'Otro')], default='LISTA_CHEQUEO', max_length=20)),
                ('descripcion', models.TextField(blank=True)),
                ('archivo_plantilla', models.FileField(blank=True, null=True, upload_to='instrumentos/')),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Instrumento de inspección',
                'verbose_name_plural': 'Catálogo: Instrumentos de inspección y seguimiento',
            },
        ),
        migrations.CreateModel(
            name='PasoPESV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveSmallIntegerField(unique=True)),
                ('nombre', models.CharField(max_length=200)),
                ('fase', models.IntegerField(choices=[(1, 'Fase 1. Planificación del PESV'), (2, 'Fase 2. Implementación y Ejecución del PESV'), (3, 'Fase 3. Seguimiento por la Organización'), (4, 'Fase 4. Mejora Continua del PESV')])),
                ('nivel_aplicable', models.CharField(choices=[('TODOS', 'Aplica para todos los niveles'), ('ESTANDAR_AVANZADO', 'Aplica para nivel Estándar y Avanzado'), ('AVANZADO', 'Aplica solo para nivel Avanzado')], default='TODOS', max_length=20)),
                ('descripcion', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Paso del PESV',
                'verbose_name_plural': 'Catálogo: 24 pasos del PESV',
                'ordering': ['numero'],
            },
        ),
        migrations.CreateModel(
            name='Componente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Código corto, p. ej. C01', max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=255)),
                ('pregunta_verificacion', models.TextField(blank=True, help_text='Pregunta orientadora que usará el auditor durante la visita.', verbose_name='Pregunta / criterio de verificación')),
                ('tipo_evidencia_esperada', models.CharField(choices=[('DOCUMENTO', 'Documento soporte únicamente'), ('EJECUCION', 'Evidencia de ejecución únicamente'), ('AMBOS', 'Documento soporte y evidencia de ejecución')], default='AMBOS', max_length=10)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
                ('paso_principal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='componentes_principales', to='pesv.pasopesv')),
                ('pasos_relacionados', models.ManyToManyField(blank=True, related_name='componentes_relacionados', to='pesv.pasopesv')),
            ],
            options={
                'verbose_name': 'Componente verificable',
                'verbose_name_plural': 'Catálogo: Componentes verificables',
                'ordering': ['orden', 'paso_principal__numero'],
            },
        ),
    ]
