# Generated by Django 5.0.14 on 2026-06-22 02:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0001_initial'),
        ('pesv', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramaAnualVerificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.PositiveIntegerField(unique=True, verbose_name='Año')),
                ('nombre', models.CharField(blank=True, max_length=255)),
                ('objetivo', models.TextField(blank=True)),
                ('alcance', models.TextField(blank=True)),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('APROBADO', 'Aprobado'), ('EN_EJECUCION', 'En ejecución'), ('CERRADO', 'Cerrado')], default='BORRADOR', max_length=15)),
                ('fecha_aprobacion', models.DateField(blank=True, null=True)),
                ('aprobado_por', models.CharField(blank=True, max_length=200)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Programa anual de verificación',
                'verbose_name_plural': 'Programas anuales de verificación',
                'ordering': ['-anio'],
            },
        ),
        migrations.CreateModel(
            name='VisitaProgramada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_programada', models.DateField()),
                ('fecha_real', models.DateField(blank=True, null=True)),
                ('duracion_horas_estimada', models.DecimalField(decimal_places=1, default=4, max_digits=4)),
                ('estado', models.CharField(choices=[('PROGRAMADA', 'Programada'), ('REPROGRAMADA', 'Reprogramada'), ('REALIZADA', 'Realizada'), ('CANCELADA', 'Cancelada')], default='PROGRAMADA', max_length=15)),
                ('observaciones', models.TextField(blank=True)),
                ('componentes_a_evaluar', models.ManyToManyField(blank=True, related_name='visitas_programadas', to='pesv.componente')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitas_programadas', to='empresas.empresa')),
                ('equipo_auditor', models.ManyToManyField(blank=True, limit_choices_to={'is_active': True}, related_name='visitas_asignadas', to=settings.AUTH_USER_MODEL)),
                ('instrumentos', models.ManyToManyField(blank=True, related_name='visitas_programadas', to='pesv.instrumentoinspeccion')),
                ('pasos_a_evaluar', models.ManyToManyField(blank=True, help_text='Número de pasos del PESV (de los 24) a evaluar en esta visita.', related_name='visitas_programadas', to='pesv.pasopesv')),
                ('programa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitas', to='programa.programaanualverificacion')),
            ],
            options={
                'verbose_name': 'Visita programada',
                'verbose_name_plural': 'Cronograma de visitas',
                'ordering': ['fecha_programada'],
            },
        ),
    ]
