# Generated by Django 5.0.14 on 2026-06-22 02:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, verbose_name='Razón social')),
                ('nit', models.CharField(max_length=30, unique=True, verbose_name='NIT')),
                ('tipo_organizacion', models.CharField(choices=[('PUBLICA', 'Pública'), ('PRIVADA', 'Privada'), ('MIXTA', 'Mixta')], default='PRIVADA', max_length=10)),
                ('misionalidad', models.CharField(choices=[('TRANSPORTE', 'Misionalidad 1: Prestación del servicio de transporte'), ('OTRA', 'Misionalidad 2: Otra (contrata o administra conductores)')], default='OTRA', max_length=12)),
                ('nivel_pesv', models.CharField(choices=[('BASICO', 'Básico'), ('ESTANDAR', 'Estándar'), ('AVANZADO', 'Avanzado')], default='BASICO', help_text='Determina qué pasos del PESV son exigibles a la organización.', max_length=10, verbose_name='Nivel PESV')),
                ('sector_economico', models.CharField(blank=True, max_length=150)),
                ('direccion', models.CharField(blank=True, max_length=255)),
                ('telefono', models.CharField(blank=True, max_length=30)),
                ('email_contacto', models.EmailField(blank=True, max_length=254)),
                ('representante_legal', models.CharField(blank=True, max_length=200)),
                ('nombre_lider_pesv', models.CharField(blank=True, max_length=200, verbose_name='Líder del PESV designado')),
                ('cargo_lider_pesv', models.CharField(blank=True, max_length=150)),
                ('telefono_lider_pesv', models.CharField(blank=True, max_length=30)),
                ('email_lider_pesv', models.EmailField(blank=True, max_length=254)),
                ('numero_sedes', models.PositiveIntegerField(default=1, verbose_name='Cantidad de sedes')),
                ('numero_vehiculos', models.PositiveIntegerField(default=0, verbose_name='Cantidad de vehículos')),
                ('numero_conductores', models.PositiveIntegerField(default=0, verbose_name='Cantidad de conductores/colaboradores')),
                ('numero_contratistas', models.PositiveIntegerField(default=0, verbose_name='Cantidad de contratistas')),
                ('activa', models.BooleanField(default=True)),
                ('observaciones', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=20)),
                ('tipo_vehiculo', models.CharField(blank=True, max_length=100)),
                ('modelo', models.CharField(blank=True, max_length=20, verbose_name='Modelo / año')),
                ('propiedad', models.CharField(choices=[('PROPIO', 'Propio'), ('CONTRATADO', 'Contratado / tercerizado'), ('LEASING', 'Leasing / Renting')], default='PROPIO', max_length=12)),
                ('soat_vigencia', models.DateField(blank=True, null=True, verbose_name='Vigencia SOAT')),
                ('rtm_vigencia', models.DateField(blank=True, null=True, verbose_name='Vigencia revisión técnico-mecánica')),
                ('estado_llantas_sistemas_seguridad', models.CharField(blank=True, max_length=200, verbose_name='Estado llantas / sistemas de seguridad')),
                ('activo', models.BooleanField(default=True)),
                ('observaciones', models.TextField(blank=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehiculos', to='empresas.empresa')),
            ],
            options={
                'verbose_name': 'Vehículo',
                'verbose_name_plural': 'Vehículos',
                'ordering': ['empresa', 'placa'],
            },
        ),
        migrations.CreateModel(
            name='Conductor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres_apellidos', models.CharField(max_length=200)),
                ('numero_documento', models.CharField(max_length=30)),
                ('tipo_vinculacion', models.CharField(blank=True, help_text='Empleado directo, contratista, tercerizado, etc.', max_length=50)),
                ('licencia_categoria', models.CharField(blank=True, max_length=20)),
                ('licencia_vigencia', models.DateField(blank=True, null=True, verbose_name='Vigencia licencia de conducción')),
                ('licencia_documento', models.FileField(blank=True, null=True, upload_to='conductores/licencias/')),
                ('examen_medico_fecha', models.DateField(blank=True, null=True, verbose_name='Fecha último examen médico')),
                ('examen_medico_vigencia', models.DateField(blank=True, null=True, verbose_name='Vigencia examen médico')),
                ('examen_medico_resultado', models.CharField(blank=True, choices=[('APTO', 'Apto'), ('APTO_RESTRICCIONES', 'Apto con restricciones'), ('NO_APTO', 'No apto')], max_length=20)),
                ('examen_medico_documento', models.FileField(blank=True, null=True, upload_to='conductores/examenes_medicos/')),
                ('comparendos_verificado', models.BooleanField(default=False, verbose_name='Comparendos verificados')),
                ('comparendos_fecha_verificacion', models.DateField(blank=True, null=True)),
                ('comparendos_observaciones', models.TextField(blank=True)),
                ('comparendos_soporte', models.FileField(blank=True, null=True, upload_to='conductores/comparendos/')),
                ('competencias_fecha_evaluacion', models.DateField(blank=True, null=True)),
                ('competencias_resultado', models.CharField(blank=True, max_length=100)),
                ('competencias_documento', models.FileField(blank=True, null=True, upload_to='conductores/competencias/')),
                ('jornada_horas_promedio_dia', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('fatiga_controles_aplicados', models.TextField(blank=True, help_text='Pausas activas, rotación de turnos, monitoreo de horas de conducción, etc.', verbose_name='Controles de fatiga aplicados')),
                ('fatiga_soporte', models.FileField(blank=True, null=True, upload_to='conductores/fatiga/')),
                ('es_reincidente', models.BooleanField(default=False, verbose_name='Conductor reincidente')),
                ('detalle_reincidencia', models.TextField(blank=True)),
                ('plan_seguimiento_reincidencia', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conductores', to='empresas.empresa')),
            ],
            options={
                'verbose_name': 'Conductor',
                'verbose_name_plural': 'Conductores',
                'ordering': ['empresa', 'nombres_apellidos'],
                'unique_together': {('empresa', 'numero_documento')},
            },
        ),
    ]
